# SPDX-FileCopyrightText: Meta Platforms, Inc. and its affiliates
# SPDX-FileCopyrightText: TNG Technology Consulting GmbH <https://www.tngtech.com>
#
# SPDX-License-Identifier: Apache-2.0

name: Sync Node.js version with Electron

on:
  push:
    branches:
      - 'renovate/electron*'
    paths:
      - 'package.json'

jobs:
  sync-node-version:
    runs-on: ubuntu-latest
    # Skip if the last commit was made by this workflow
    if: "!contains(github.event.head_commit.message, 'chore(sync-node-version)')"
    permissions:
      contents: write
    env:
      CI: true
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - uses: actions/setup-node@v6
        with:
          cache: 'yarn'
          node-version-file: '.nvmrc'

      - run: yarn install --immutable

      - run: yarn sync-node-version

      - name: Commit changes
        uses: planetscale/ghcommit-action@25309d8005ac7c3bcd61d3fe19b69e0fe47dbdde # v0.2.20
        with:
          commit_message: 'chore(sync-node-version): sync Node.js version with Electron'
          repo: ${{ github.repository }}
          branch: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
